### ISSUE TITLE
我又用了一次这个算法哈哈哈

### ISSUE THREAD

**Issue by smallst** [MKimiSH/PixMix-inpainting#2]
研究生课大作业想不到写什么于是又用了次这个暴力的物体检测方法做了另外一个作业233333

**Comment by smallst** [comment]
哦等等，忘了关键问题，我又用在了张超的课上……
不知道他还记不记得这个东西哈哈哈

**Comment by zhangyu94** [comment]
2333:joy:

**Comment by MKimiSH** [comment]
How did you use it 23333

**Comment by smallst** [comment]
一个视频物体分割任务，需要第一帧的label，就拿这个东西画label 23333合情合理
